name: "fal_011"
version: "1.0.0"
config-version: 2
profile: "fal_test"
model-paths: ["models"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
vars:
  fal-scripts-path: "scripts"
  fal-models-paths: ["fal_models"]
